### ISSUE TITLE
HU - Logs

### ISSUE THREAD

**Issue by harvestcore** [harvestcore/HarvestCCode#14]
As a user I want to be able to get logs to see at any moment what is happening in the system, so in the case something happens I'm able to know where the process of fetching data with the updaters failed.

- **Given:** That I want to know the status of the system
- **When:** I issue an API request to the logs endpoint
- **Then:** I get all the events that happened in the system

**Comment by harvestcore** [comment]
https://github.com/harvestcore/HarvestCCode/commit/3db9972fed8e6fd1c17439c1c216dca3bdfe7eaa

**Comment by JJ** [comment]
Not clear why you want to do this part of the application, and not simply part of the infrastructure. What kind of user would want the raw logs? If it's an admin, can he or she simply download it form the log service? Creating a two-way communication line between them creates lots of problems, and not really any kind of solution. Besides, no added value here. If anything, it should be part of _a different_ microservice.
