### ISSUE TITLE
HU - Fetch data from time to time

### ISSUE THREAD

**Issue by harvestcore** [harvestcore/HarvestCCode#15]
As a user I want the software to be able to fetch data from a source with a given schema when a time interval is met, so I don't need to perform that action by myself.

- **Given:** I want to fecth data from an endpoint and I've already created one or more updaters
- **When:** The time interval is met
- **Then:** The data is fetch

**Comment by JJ** [comment]
What kind of data? Why would you have to fetch that data via POST exclusively? Why don't you do it via curl + cron?
