### ISSUE TITLE
HU - Store the fetched data

### ISSUE THREAD

**Issue by harvestcore** [harvestcore/HarvestCCode#16]
As a user I want the software to store the data that it is fetch with the updaters, so I can consult that data when I want.

- **Given:** I have created one or more updaters
- **When:** Everytime the time interval is met and the updaters fetch data
- **Then:** The data is stored in a (MongoDB) collection that has the same schema provided when creating the updater

**Comment by JJ** [comment]
I would like to see some discussion here on what you are storing, and what's the best way to fetch it. I still don't get what kind of "data" you're looking for and the problem you want to solve.

**Comment by JJ** [comment]
Also, you are mixing implementation details with user requirements.

**Comment by harvestcore** [comment]
@JJ

> I would like to see some discussion here on what you are storing, and what's the best way to fetch it.

I'm only storing what the user wants to store.

Let's say:
- A user wants to fetch data from the endpoint _mycoolapi.com/data_.
- The schema of the data is: `{ id: int, name: string, age: int }`
- The time interval is 3600s.

If the data fetched from the endpoint has the schema `{ id: int, name: string, surname: string, birthdate: int, age: int }` only the data that fits the schema specified will be stored in the DB (so _surname_ and _birthdate_ keys won't be stored).
